version: '3'

services:
  frontend:
    container_name: smart-home-frontend
    image: ryanlaycock/smart-home-frontend:0.0.1
    ports:
      - 80:80
    depends_on:
      - smart-home-api
    restart: always
    command: nginx -g 'daemon off';

  smart-home-api:
    container_name: smart-home-api
    image: ryanlaycock/smart-home-api:0.0.1
    hostname: smart-home-api
    restart: always
    volumes:
      - ./config.json:/app/config.json
    expose:
      - 8080
    environment:
      - CONFIG_FILE=config.json