# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import sensors_pb2 as protos_dot_sensors__pb2


class SensorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Read = channel.unary_unary(
                '/sensors.Sensor/Read',
                request_serializer=protos_dot_sensors__pb2.ReadParams.SerializeToString,
                response_deserializer=protos_dot_sensors__pb2.Reading.FromString,
                )


class SensorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=protos_dot_sensors__pb2.ReadParams.FromString,
                    response_serializer=protos_dot_sensors__pb2.Reading.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sensors.Sensor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Sensor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sensors.Sensor/Read',
            protos_dot_sensors__pb2.ReadParams.SerializeToString,
            protos_dot_sensors__pb2.Reading.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
